### ISSUE TITLE
aln.iupac_consensus doesn't work as expected

### ISSUE THREAD

**Issue by dgslos** [cogent3/cogent3#1278]
**Describe the bug**
aln.iupac_consensus produces a string with only "???" instead of a sequence string with IUPAC codes.

**To Reproduce**
```
aln = load_aligned_seqs("my_file.fasta", moltype="dna")
iupac_consensus = aln.iupac_consensus(alphabet=None)
print(iupac_consensus)
```
This produces only "????????" instead of a sequence with IUPAC codes

**Expected behavior**
Consenus sequences with IUPAC codes

**Comment by GavinHuttley** [comment]
What version of cogent3 are you using?
```python
import cogent3

print(cogent3.__version__)
```

Putting in a concrete example
```python
from cogent3 import load_aligned_seqs

aln = load_aligned_seqs("https://raw.githubusercontent.com/cogent3/cogent3/develop/doc/data/F9-demo.fa", moltype="dna")
iupac_consensus = aln.iupac_consensus(alphabet=None)
print(iupac_consensus)
```
on my machine, this produces
```
AAR???TAYGTTGATGGAGATCAGTGTGARTCMAATCCDTGYTTAAATGGYGGMAKWTGYAAGGATGAYATTARTTCCTATGAATGYTGGTGYCVMBYTGGATTYGAAGGRARGAACTGTGAATTAGATGYAWCRTGYARCATTAARAAT
```
So perhaps something special about `"my_file.fasta"`?

**Comment by dgslos** [comment]
I found the reason. Every gap produces a '?', even if thousand sequences don't have a gap on that position. If you have a huge alignment, the change of having a shorter sequence or an alignment where you have the first part sequenced for a number of sequences and the second part for another number of sequences and some full length, this will always produce '????' in the IUPAC consensus. Adding an ignore gaps option would be handy. 

Try again with this:
``` 
>Mouse Lemur
--------------------------------CAATCCGTGTTTAAATGGTGGCAGTTGC
AAGGATGACATTAATTCCTATGAATGTTGGTGTCGACTTGGATTTGAAGGGAGGAACTGT
GAATTAGATGCATCATGCAGCATTAAGAAT
>Rat
AAGCAGTATGTTGATGGAGATCAGTGTGAATCAAATCCTTGCTTAAATGGTGGAATATGC
AAGGATGATATTAATTCCTATGAATGTTGGTGCCAAGCTGGATTTGAAGGAAGGAACTGT
GAA---------------------------
>Mouse
AAGCAGTATGTTGATGGAGATCAGTGTGAATCAAATCCTTGTTTAAATGGTGGAATATGC
AAGGATGATATTAGTTCCTATGAATGCTGGTGCCAAGTTGGATTTGAAGGAAGGAACTGT
GAATTAGATGCAACGTGTAACATTAAAAAT
>Macaque
AAGCAGTATGTTGATGGAGATCAGTGTGAGTCCAATCCATGTTTAAATGGTGGCAGTTGT
AA----------------------------------------------------------
------------------------------
>Human
------TATGTTGATGGAGATCAGTGTGAGTCCAATCCATGTTTAAATGGCGGCAGTTGC
AAGGATGACATTAATTCCTATGAATGTTGGTGTCCCTTTGGATTTGAAGGAAAGAACTGT
GAATTAGATGTAACATGTAACATTAAGAAT
>Chimp
------------------------------------------------------------
----ATGACATTAATTCCTATGAATGTTGGTGTCCATTTGGATTTGAAGGAAAGAACTGT
GAATTAGATGTAACATGTAACATTAAGAAT
```

**Comment by GavinHuttley** [comment]
I agree, adding an option to ignore gaps would be very handy. Using the pattern from other methods, something like
```python
aln.iupac_consensus(allow_gap=False)
```
What follows is how I'm solving this for future reference for others who might want to tackle these problems themselves and make a pull request (which I would absolutely love).

## Writing a test to illustrate the problem

A good test is one that is small, but clearly illustrates the problem.

Illustrate the current behaviour
```python
from cogent3 import make_aligned_seqs

aln = make_aligned_seqs(data={"s1": "ACGG", "s2": "ACGG", "s3": "-CGG"}, moltype="dna")
```
Here's the desired new interface and outcome
```python
assert aln.iupac_consensus(allow_gap=False) == "?CGG"
```
A few points on design.

1. The sample sequences are also valid RNA and PROTEIN mol type sequences, since we need to test the change works for all those molecular types too.
2. the assert statements are there because when I put that code in one a test file, those statements will both pass only when the new feature has been implemented.
3. I'm using `allow_gap` because the same argument is used in other methods. Since this is a modification of code being used by others, the default value for that new argument should be the one that results in the current behaviour (hence how I've written those two tests).
4. We have to do 2 separate implementations, an annoying side effect of having `Alignment` and `ArrayAlignment` classes whose underlying data types are very different. (We are aiming to merge these two later this year, but for now we have to deal with both.)

## Where to put the tests

In `cogent3/tests/test_core/test_alignment.py`

## How to write the tests

Project wide, we are moving to using pytest throughout. So that's what we will do here. We need to test a matrix made up of the two alignment classes and the 3 molecular types. This is great case for pytest fixtures!

## Finally

When you receive a notification this issue has been closed, you can look at the code linked to it to see what was done. To use that new feature you will need to uninstall your cogent3 and install the development version directly from github. (Instructions in the README.)

And thanks for raising this!

**Comment by dgslos** [comment]
And even better, add a treshold. For example, an IUPAC code (not gap) should be seen in x% of the total sequences, else write "?" (or N) in case there are more gaps then allowed by the treshold.

**Comment by GavinHuttley** [comment]
I'm about to merge the PR addressing the allow_gaps feature which will automatically close this issue.

Can you please create a new issue with this new feature request.

It would be ideal if you can take the approach I've illustrated above to writing tests of the new feature you want since that will illustrate the behaviour precisely..

If you wanted to implement this yourself and make a contribution, I'd be happy to help you do that! But let's move all that discussion to a new issue.
