### ISSUE TITLE
ENH: write a db wrapper class for handling annotations etc...

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#1749]
Our current annotation Db handling class implementations are tightly hooked to Sqlite3 syntax and features. To support other backends, we need to define the db interface so that our Gff3 and Genbank class implementations are not coupled to the semantics of the different backends. Specific targets to address are Sqlite3 and DuckDb.

As discussed in #1747 , the `sqlite3` context manager on a connection is transaction-based, whilst for duckdb, it's connection-based.

A draft of this is all that's required for now, pushed to a new branch.

**Comment by rmcar17** [comment]
Just documenting my thoughts on this as I begin to plan this out.

We want something that is essentially a wrapper around how the `db` property (and sometimes `self._db`) of the `SqliteAnnotationDbMixin` class is used so that it is agnostic towards whether it uses a DuckDB or sqlite backend.

Relatively simple things, like executing basic SQL statements, committing etc. I believe should be trivial. Just calling the respective methods on each of the sqlite or duckdb objects (could have an abstract property in the base class with default behaviour, though for extensibility if another db pops up in the future, it would be best to define these in the implementation classes).

Care should be taken with things such as `with` to ensure consistent behaviour (in sqlite transactions are committed on exit, in duckDB the connection is closed - the former is very much preferred). TODO check if any other code is called on context manager exit.

One slightly more challenging thing is ensuring that the format in which the data returned is consistent. Currently the `sqlite3` row factory is used to which there is not an analog in DuckDB. DuckDB allows the return of a dictionary of `numpy` arrays, a `pandas` df, etc. a listed [here](https://duckdb.org/docs/api/python/overview.html#result-conversion). All likely with their own performance implications. It is important that the type of data that is returned is consistent so results can be used in the same way (TODO investigate which is best).

Likely the most challenging part is dealing with slight differences in data types between [sqlite3](https://www.sqlite.org/datatype3.html) and [DuckDB](https://duckdb.org/docs/sql/data_types/overview.html). For instance, `REAL` in sqlite3 is a float64, whereas in DuckDB `REAL` is a float32 (they have `DOUBLE` which is a float64). While that datatype isn't specifically used in cogent3, it is something important to keep in mind during development to ensure consistent behaviour (or do we accept small differences in behaviour over the different backends? Probably good to keep the size of the types the same).

Also of note along those lines is the ability of sqlite3 to store custom data types in python (e.g. how we have done with `array`). We can perform a similar trick in DuckDB to what we did with sqlite3 by converting it to the .npy format and storing it in a `BLOB` (variable length binary data). However, DuckDB also allows data arrays of known sizes, or lists, to be stored directly which I assume is more performant. 

The short of the above is we need different database schemas depending on whether we are using the Sqlite3 backend or the DuckDB backend. We would likely need to define a mapping of the types that we choose in the schemas of, for instance `GenbankAnnotationDb`, into the correct types for the relevant backends. This mapping should be stored in the implementation side of our wrapper.

**Comment by GavinHuttley** [comment]
I think the proxy class should know nothing of the backends, but address API usability issues (like context management, returned types etc..) Also, differences in REAL definition are less critical in the sense that a db saved as DuckDb native does need to be interpretable by sqlite. If integers returned by both are Python native, job done.

I agree that schemas would differ between SQLite and DuckDb for one of our db's, e.g. `GenbankAnnotationDb`. I think that's essential given differences in custom type handling.

In terms of "important that the type of data that is returned is consistent", I think that's too difficult to handle generically. What I mean is there are multiple use cases of databases within cogent3, e.g. annotation handling and generic data stores. We need to leave it to defined interfaces of those individual cases to declare appropriate types. This proxy class should just be limited to basic database interactions.

The first step here is to define an abstract class for query results. For example, make the API mimic the SQLite row factory approach.

The next step is work on the

**Comment by GavinHuttley** [comment]
@rmcar17 [DuckDb supports custom functions](https://duckdb.org/docs/api/python/function.html) for serialising / deserialising as an alternate approach to the custom types

**Comment by GavinHuttley** [comment]
we could also replace the `array` custom type with a BLOB and handle conversion within, for example, the annotation db classes

**Comment by GavinHuttley** [comment]
## DuckDb stuff from @EbiArnie 

https://duckdb.org/docs/api/python/function.html
https://duckdb.org/docs/sql/data_types/array
https://duckdb.org/docs/sql/data_types/blob
https://duckdb.org/docs/sql/data_types/list

**Comment by GavinHuttley** [comment]
I'm closing this as I think the better solution is to be found based on driver plugin's and base classes.
