### ISSUE TITLE
Research producing an image gallery for the documentation

### ISSUE THREAD

**Issue by GavinHuttley** [cogent3/cogent3#533]
[See this example](https://github.com/plotly/plotly-sphinx-gallery).

The challenge is our current visualisation examples are notebook based...

**Comment by u6052029** [comment]
For the example provided, I have discovered the following:

- Sphinx-gallery only supports py files.

- However, you can mark up the py files to be styled in the same way as a notebook (https://sphinx-gallery.github.io/stable/tutorials/plot_parse.html). Which with plotly does include interactive plotly graphs on the pages.

- Export as notebook file is also supported.

-  Due to a bug with plotly's image scrapper(for thumbnails), only 1 gallery can exist in the documentation. E.g. one gallery for the top directory and one gallery for the visualizations page.

**Comment by GavinHuttley** [comment]
Do we replace all `docs/draw/*ipynb` with `.py` files or do we add `.py` files in addition to the notebooks?

**Comment by u6052029** [comment]
We would need to remove the ipynb files and replace them with py that exist in an external folder outside the docs folder.

How sphinx gallery works is that it uses py files in an external folder to generate a folder in the docs folder that contains rst, py, ipynb files for each py file. The index.rst in the generated folder is what is included in the documentation.

**Comment by GavinHuttley** [comment]
OK, create a `gallery` directory. VS code should be able to produce the correctly formatted ".py" via "Python; Import JUpyter Notebook"

**Comment by GavinHuttley** [comment]
You will also need to modify the `docs/conf.py`, the `.readthedocs.yml` and the `setupy.py` section under `extras_require`.
